export const routes = {
  home: "/",
  about: "/about",
  governance: "/about/governance",
  leadership: "/about/leadership",
  policies: "/about/policies",
  programs: "/programs",
  impact: "/impact",
  transparency: "/transparency",
  reports: "/transparency/reports",
  downloads: "/transparency/downloads",
  meFramework: "/transparency/me-framework",
  resources: "/resources",
  getInvolved: "/get-involved",
  donate: "/get-involved/donate",
  volunteer: "/get-involved/volunteer",
  partner: "/get-involved/partner",
  contact: "/contact",
} as const;
